keys:
  - &laptop age1nav5ahnklyznc0tfj7pkmtr95k7h7j3u95uj6mukp8lvkunfvywqnwvn3s
  - &desktop age12r08ljuhvznsypvt9auza4k7f5362eng3dchfcsucx0rfzgnse5s92n78u
  - &server age1ud5k6fs2vaw7k9nhl5jv3973zfcy69vrsyxs8lwwkktlsv95xg4qp2rf2q
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *laptop
      - *desktop
      - *server
