keys:
  - &old_laptop age1nav5ahnklyznc0tfj7pkmtr95k7h7j3u95uj6mukp8lvkunfvywqnwvn3s
  - &old_desktop age12r08ljuhvznsypvt9auza4k7f5362eng3dchfcsucx0rfzgnse5s92n78u
  - &old_server age1ud5k6fs2vaw7k9nhl5jv3973zfcy69vrsyxs8lwwkktlsv95xg4qp2rf2q
  - &desktop age15luh64um2extfmeqy8rmq9cqhm8c8xzh9fqcqvz58mnup3lmgvrqqq35sc
  - &server age19ss777jhrnwsnpy9ah452km0p0e4cfhmj3kyr9u7m3rh3fept4pqepavrd 
creation_rules: 
  - path_regex: secrets/.*
    key_groups:
    - age:
      - *old_laptop
      - *old_desktop
      - *old_server
      - *desktop
      - *server
